/** Key=value header blocks for MCP tool results; transcript as separate block. */

const DELIM = '\n---\n';
const TRANSCRIPT_LABEL = 'transcript:';

/** Whether the transcript came from platform subtitles (VTT) or was generated by speech-to-text. */
export type TranscriptSource = 'platform_subtitles' | 'transcription';

export interface TranscriptResponseParams {
  url: string;
  job_id: string;
  transcript: string;
  fromArchive?: boolean;
  /** URL as stored by YTPTube; use as video_url in get_status when present. */
  status_url?: string;
  /** How the transcript was obtained: platform_subtitles = from video subtitles/captions; transcription = generated from audio (e.g. Scaleway). */
  transcript_source?: TranscriptSource;
  /** ISO-639-1 or "unknown" when no language_hint; used for transcript metadata. */
  language_used?: string;
  /** When language unknown: instruct LLM to ask user and re-call with language_hint. */
  language_instruction?: string;
  /** Canonical key for this video (same key = same video); for deduplication and debugging. */
  canonical_key?: string;
}

export interface TranscriptResponseBlocks {
  metadata: string;
  transcript: string;
}

/** Two blocks for transcript: metadata (result, url, job_id, transcript_source, language_used?, language_instruction?, relay) and transcript text. */
export function formatTranscriptResponseAsBlocks(params: TranscriptResponseParams): TranscriptResponseBlocks {
  const { url, job_id, transcript, fromArchive, status_url, transcript_source, language_used, language_instruction, canonical_key } = params;
  const relay = fromArchive
    ? 'Transcript below (from archive).'
    : 'Transcript below.';
  const lines = [
    'result=transcript',
    `url=${url}`,
    `job_id=${job_id}`,
    `relay=${relay}`,
  ];
  if (status_url != null && status_url !== url) lines.push(`status_url=${status_url}`);
  if (canonical_key != null) lines.push(`canonical_key=${canonical_key}`);
  if (transcript_source != null) lines.push(`transcript_source=${transcript_source}`);
  if (language_used != null) lines.push(`language=${language_used}`);
  if (language_instruction != null) lines.push(`language_instruction=${language_instruction}`);
  const metadata = lines.join('\n');
  const transcriptText =
    (transcript_source != null ? `[transcript_source=${transcript_source}]\n` : '') +
    (transcript?.trim() || '(empty)');
  return { metadata, transcript: transcriptText };
}

/** Legacy single-string transcript response (metadata + delimiter + transcript). */
export function formatTranscriptResponse(params: TranscriptResponseParams): string {
  const { metadata, transcript } = formatTranscriptResponseAsBlocks(params);
  return `${metadata}${DELIM}${TRANSCRIPT_LABEL}\n${transcript}`;
}

export type StatusKind = 'queued' | 'downloading' | 'finished' | 'error' | 'not_found';

export interface StatusResponseParams {
  status: StatusKind;
  job_id?: string;
  url?: string;
  status_url?: string;
  progress?: number;
  reason?: string;
  relay: string;
  /** For transcript jobs: ISO-639-1 or "unknown"; same semantics as transcript language_used. */
  language?: string;
  /** When language unknown: instruct LLM to ask user and re-call with language_hint. */
  language_instruction?: string;
  /** Canonical key for this video (same key = same video); for deduplication and debugging. */
  canonical_key?: string;
}

/** Single key=value block for status (no transcript). */
export function formatStatusResponse(params: StatusResponseParams): string {
  const parts: string[] = ['result=status', `status=${params.status}`];
  if (params.job_id != null) parts.push(`job_id=${params.job_id}`);
  if (params.url != null) parts.push(`url=${params.url}`);
  if (params.status_url != null && params.status_url !== params.url) parts.push(`status_url=${params.status_url}`);
  if (params.canonical_key != null) parts.push(`canonical_key=${params.canonical_key}`);
  if (params.progress != null) parts.push(`progress=${params.progress}%`);
  if (params.reason != null) parts.push(`reason=${params.reason}`);
  if (params.language != null) parts.push(`language=${params.language}`);
  if (params.language_instruction != null) parts.push(`language_instruction=${params.language_instruction}`);
  parts.push(`relay=${params.relay}`);
  return parts.join('\n');
}

/** Error response: result=error, relay=message. */
export function formatErrorResponse(message: string): string {
  return `result=error\nrelay=${message}`;
}

export interface DownloadLinkResponseParams {
  download_url: string;
  relay: string;
  /** Video URL this link belongs to; for context. */
  url?: string;
  /** Canonical key for this video (same key = same video); for deduplication and debugging. */
  canonical_key?: string;
}

/** Key=value block for download link tool (download_url, relay). */
export function formatDownloadLinkResponse(params: DownloadLinkResponseParams): string {
  const lines = [`download_url=${params.download_url}`];
  if (params.url != null) lines.push(`url=${params.url}`);
  if (params.canonical_key != null) lines.push(`canonical_key=${params.canonical_key}`);
  lines.push(`relay=${params.relay}`);
  return lines.join('\n');
}

/** Single line for one item in list_recent_downloads (title, status, url, optional download_url, canonical_key). */
export function formatListRecentDownloadsItem(params: {
  title: string;
  status: string;
  url?: string;
  job_id?: string;
  download_url?: string;
  /** Canonical key for this video (same key = same video); for deduplication and debugging. */
  canonical_key?: string;
}): string {
  const parts = [
    `title=${params.title}`,
    `status=${params.status}`,
  ];
  if (params.url != null) parts.push(`url=${params.url}`);
  if (params.job_id != null) parts.push(`job_id=${params.job_id}`);
  if (params.download_url != null) parts.push(`download_url=${params.download_url}`);
  if (params.canonical_key != null) parts.push(`canonical_key=${params.canonical_key}`);
  return parts.join('\t');
}

/** Key=value block for get_video_info (title, duration, extractor, relay). */
export function formatVideoInfoResponse(params: {
  title?: string;
  duration?: number;
  extractor?: string;
  relay: string;
  [key: string]: string | number | undefined;
}): string {
  const lines: string[] = ['result=video_info'];
  if (params.title != null) lines.push(`title=${params.title}`);
  if (params.duration != null) lines.push(`duration=${params.duration}`);
  if (params.extractor != null) lines.push(`extractor=${params.extractor}`);
  lines.push(`relay=${params.relay}`);
  return lines.join('\n');
}

/** Key=value block for get_thumbnail_url (thumbnail_url, relay). */
export function formatThumbnailUrlResponse(params: { thumbnail_url: string; relay: string }): string {
  return `thumbnail_url=${params.thumbnail_url}\nrelay=${params.relay}`;
}
